#!/bin/sh

[ ! -d "${XDG_CONFIG_HOME}/stylish-haskell" ] && \
    mkdir -p "${XDG_CONFIG_HOME}/stylish-haskell"

stow \
    --target="${HOME}" \
    --ignore="^@.*" \
    --verbose \
    stylish-haskell
