export EDITOR="vim"
export VISUAL="vim"
export PAGER="less"
export DIFF="colordiff"
export BROWSER="links"

export DOTNET_CLI_TELEMETRY_OPTOUT=1
export DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1
export EIX_LIMIT=50
export FZF_DEFAULT_OPTS="--height 20% --reverse --border"
export GCC_COLORS=1
export HISTSIZE=100000
export KEYTIMEOUT=1
export NUGET_XMLDOC_MODE="skip"
export RANGER_LOAD_DEFAULT_RC=false
export SAVEHIST=100000

export CARGO_HOME="${HOME}/.cargo"
export GNUPGHOME="${HOME}/.gnupg"
export GOPATH="${HOME}/.go"
export LESSHISTFILE="/dev/null"
export NNN_TMPFILE="${XDG_CACHE_HOME}/nnn_tmpfile"
export PGPASSFILE="${XDG_CONFIG_HOME}/postgrsql/pass"
export PGSERVICEFILE="${XDG_CONFIG_HOME}/postgresql/service.conf"
export PSQLRC="${XDG_CONFIG_HOME}/postgresql/sqlrc"
export PSQL_HISTORY="${XDG_DATA_HOME}/postgrsql/history"
export PYTHONSTARTUP="${HOME}/.pystartup"
export SCREENRC="${XDG_CONFIG_HOME}/screen/screenrc"
export WEECHAT_HOME="${HOME}/.weechat"
export WEECHAT_PASSPHRASE="${HOME}/.weechat/passphrase"
