#!/usr/bin/env bash

FILES=()
while read -r
do
    FILES+=("$REPLY")
done

while read file
do
    case "$1" in
        "C-c")
            echo -en "${FILES[@]}" | xclip -selection clipboard
            ;;
        "C-f")
            xclip -selection clipboard -target image/png "${FILES[@]}"
            ;;
        "C-d")
            rm -f "${FILES[@]}"
            ;;
    esac
done
