#!env zsh

alias beet="beet -c $XDG_CONFIG_HOME/beets/config.yaml"
alias cal="cal --three --monday"
alias cp="cp --verbose"
alias crypto="curl rate.sx"
alias d="doom run"
alias disk="lsblk -o NAME,TYPE,FSTYPE,LABEL,UUID,SIZE,MOUNTPOINT"
alias e="emacs --no-window-system"
alias ec="emacsclient --no-window-system"
alias egrep="egrep --color=auto --ignore-case"
alias euses="euses --colour"
alias fc-list-c="fc-list :lang=zh | sort"
alias fc-list-j="fc-list :lang=ja | sort"
alias fc-list-k="fc-list :lang=ko | sort"
alias fgrep="fgrep --color=auto --ignore-case"
alias fs="df --human-readable --portability --sync --print-type --exclude-type=tmpfs --exclude-type=devtmpfs"
alias g="git"
alias genqr="curl -F-=\<- qrenco.de"
alias grep="grep --color=auto --ignore-case"
alias gtypist="gtypist --max-error=100.0 --notimer --term-cursor --curs-flash=10 --silent --word-processor --show-errors --always-sure --scoring=wpm"
alias la="ls --group-directories-first --time-style=+\"%d.%m.%y %H:%M\" --indicator-style=classify --color=auto --human-readable -l --all"
alias lg="ls --group-directories-first --time-style=+\"%d.%m.%y %H:%M\" --indicator-style=classify --color=auto --human-readable -l --all | grep"
alias ll="ls --group-directories-first --time-style=+\"%d.%m.%y %H:%M\" --indicator-style=classify --color=auto --human-readable -l"
alias ls="ls --group-directories-first --time-style=+\"%d.%m.%y %H:%M\" --indicator-style=classify --color=auto --human-readable"
alias mem="free --human --wide"
alias mkdir="mkdir --verbose --parents"
alias mv="mv --verbose"
alias myip-dns="dig +short myip.opendns.com @resolver1.opendns.com"
alias myip="curl curlmyip.net"
alias n="nnn"
alias o="xdg-open"
alias rg="rg --color=auto --ignore-case"
alias rm="rm --verbose --interactive=once"
alias rmdir="rmdir --verbose --parents"
alias rsync-cp="rsync --archive --compress --verbose --progress --human-readable"
alias rsync-mv="rsync --archive --compress --verbose --progress --human-readable --remove-source-files"
alias rsync-sync="rsync --archive --compress --verbose --progress --human-readable --update --delete"
alias rsync-update="rsync --archive --compress --verbose --progress --human-readable --update"
alias shot="maim --format=png --hidecursor --quality 8"
alias sx="startx -- vt1 -nolisten tcp"
alias t="tmux"
alias tewisay="$GOPATH/bin/tewisay -f $GOPATH/src/github.com/lucy/tewisay/cows/tes.cow"
alias torrentinfo="torrentinfo --everything"
alias units="units --history=$XDG_DATA_HOME/units_history"
alias v="vim"
alias weather="curl wttr.in/Moscow"
alias wget="wget --hsts-file=$XDG_DATA_HOME/wget-hsts"
alias wine-play="wine explorer.exe /desktop=default,1600x900"
alias xsel="xsel --logfile $XDG_DATA_HOME/xsel.log"
