* dotfiles
** Layout
Configuration files are split between different directories named after a
specific tool.
** Management
I manage everything with a thingy called GNU
[[https://www.gnu.org/software/stow/][stow]], usually by executing the
=@install= script from the root of this repository as =./category/@install=.

There are also a few scripts here that require external /bins/ from my
[[https://github.com/azahi/bin][bin]] repository. You should probably add
these in your =PATH= in case you want to mimic my settings.
** Software
*** Editor
**** Emacs
My configuration is [[https://github.com/azahi/.emacs.d][here]]. I don't like
the default keybindings that Emacs provides, also I prefer the Vim's modal
approach of editing text. To make Emacs a bit better I allow myself a bit of
religious blasphemy in using
[[https://github.com/emacs-evil/evil][evil-mode]].
**** Vim
I use [[https://github.com/neovim/neovim][NeoVim]]. It's just better than the
default /Vim experience/. It has a lot of plugins 'n stuff. It's good. Gets
the job done for small-scale projects and quick editing.
*** Terminal
It's a fork of [[https://st.suckless.org/][st]] and it's
[[https://github.com/azahi/st][here]].
*** Window Manager
**** dwm
I like [[https://dwm.suckless.org/][dwm]]. My fork of it is located
[[https://github.com/azahi/dwm][here]].
**** XMonad
My [[https://github.com/xmonad/xmonad][XMonad]] configuration is
[[https://github.com/azahi/xmonad-config][here]]. It's no longer actively
maintained because I'm not interested in it anymore.
*** Web Browser
I mainly use [[https://github.com/qutebrowser/qutebrowser][qutebrowser]].
Sometimes when I need to use a more, dare I say, normal browser I launch
[[https://www.mozilla.org/en-US/firefox/new/][Firefox]], it usually is left
alsmot unchanged apart from a couple of freshly installed plugins.
** Screenshots
A small history of my desktop alterations can be found
[[https://v.teknik.io/v/kqFNt][here]]. The more recent stuff is at the bottom.
