#!/bin/sh

[ ! -d "$HOME/.config/fcitx" ] && \
    mkdir -p "$HOME/.config/fcitx"
[ ! -d "$HOME/.config/fcitx/addon" ] && \
    mkdir -p "$HOME/.config/fcitx/addon"
[ ! -d "$HOME/.config/fcitx/conf" ] && \
    mkdir -p "$HOME/.config/fcitx/conf"
[ ! -d "$HOME/.config/fcitx/skin" ] && \
    mkdir -p "$HOME/.config/fcitx/skin"

stow \
    --target="$HOME" \
    --ignore="^@.*" \
    --verbose \
    fcitx
