#!/bin/sh

[ ! -d "${XDG_CONFIG_HOME}/fcitx" ] && \
    mkdir -p "${XDG_CONFIG_HOME}/fcitx"
[ ! -d "${XDG_CONFIG_HOME}/fcitx/addon" ] && \
    mkdir -p "${XDG_CONFIG_HOME}/fcitx/addon"
[ ! -d "${XDG_CONFIG_HOME}/fcitx/conf" ] && \
    mkdir -p "${XDG_CONFIG_HOME}/fcitx/conf"
[ ! -d "${XDG_CONFIG_HOME}/fcitx/skin" ] && \
    mkdir -p "${XDG_CONFIG_HOME}/fcitx/skin"

stow \
    --target="$HOME" \
    --ignore="^@.*" \
    --verbose \
    fcitx
