#!/bin/sh

[ ! -d "${XDG_CONFIG_HOME}/ncmpcpp" ] && \
    mkdir -p "${XDG_CONFIG_HOME}/ncmpcpp"
[ ! -d "${XDG_DATA_HOME}/ncmpcpp" ] && \
    mkdir -p "${XDG_DATA_HOME}/ncmpcpp"
[ ! -d "${XDG_DATA_HOME}/ncmpcpp/lyrics" ] && \
    mkdir -p "${XDG_DATA_HOME}/ncmpcpp/lyrics"

stow \
    --target="${HOME}" \
    --ignore="^@.*" \
    --verbose \
    ncmpcpp
