#!/bin/sh

cd || exit "$?"

if [ -f "${HOME}/.profile" ]
then
    # shellcheck disable=SC1090
    . "${HOME}/.profile"
fi

if command -v xset >/dev/null 2>&1
then
    xset m 3/2 3 &
    xset r rate 200 50 &
fi

if command -v dbus-launch >/dev/null 2>&1 \
&& [ -z "${DBUS_SESSION_BUS_ADDRESS}" ]
then
    if [ "${HOST}" != "sava" ]
    then
        eval "$(dbus-launch --sh-syntax --exit-with-x11)"
    else
        eval "$(dbus-launch --sh-syntax --exit-with-session)"
    fi
fi

if command -v xrdb >/dev/null 2>&1 \
&& [ -f "${HOME}/.xresources" ]
then
    xrdb "${HOME}/.xresources"
fi

if command -v hsetroot >/dev/null 2>&1 \
&& command -v xgetres >/dev/null 2>&1
then
    hsetroot -solid "$(xgetres background)" &
fi

if command -v setxkbmap >/dev/null 2>&1
then
    setxkbmap \
        -layout "us,ru" \
        -option "grp:win_space_toggle,compose:menu,caps:escape,terminate:ctrl_alt_bksp" &
fi

if command -v xbindkeys >/dev/null 2>&1 \
&& [ -f "${HOME}/.xbindkeysrc" ]
then
    xbindkeys &
fi

if command -v unclutter >/dev/null 2>&1
then
    unclutter --timeout 3 --ignore-scrolling --fork &
fi

if command -v autocutsel >/dev/null 2>&1
then
    autocutsel -fork &
    autocutsel -fork -selection PRIMARY &
fi

if command -v picom >/dev/null 2>&1
then
    picom --daemon &
elif command -v compton >/dev/null 2>&1
then
    compton -b &
fi

if command -v mpd-init >/dev/null 2>&1
then
    mpd-init &
fi

if command -v gpg-connect-agent >/dev/null 2>&1
then
    gpg-connect-agent updatestartuptty /bye &
fi

if command -v uim-xim >/dev/null 2>&1
then
    uim-xim --async >/dev/null 2>&1 &
fi

if command -v urxvtd >/dev/null 2>&1
then
    urxvtd --quiet --opendisplay --fork &
fi

for WM in dwm 2bwm xmonad-ng xmonad
do
    if command -v "${WM}" >/dev/null 2>&1
    then
        if [ "${WM}" = "dwm" ] \
        && command -v dwm-status >/dev/null 2>&1
        then
            dwm-status &
        fi

        if command -v dbus-launch >/dev/null 2>&1
        then
            dbus-launch --exit-with-session "${WM}"
        else
            exec "${WM}"
        fi
    fi
done
