#!/bin/sh

[ ! -d "${HOME}/.vim" ] && \
    mkdir -p "${HOME}/.vim"

stow \
    --target="${HOME}" \
    --ignore="^@.*" \
    --verbose \
    vim

if command -v nvim >/dev/null 2>&1 && [ ! -f "${XDG_CONFIG_HOME}/nvim/init.vim" ]
then
    mkdir -p "${XDG_CONFIG_HOME}/nvim"
    ln -s "${HOME}/.vim/vimrc" "${XDG_CONFIG_HOME}/nvim/init.vim"
fi
