#!/bin/sh

[ ! -d "${HOME}/.xresources.d" ] && \
    mkdir -p "${HOME}/.xresources.d"

stow \
    --target="${HOME}" \
    --ignore="^@.*" \
    --verbose \
    xresources

if [ -z "${URXVT_PERL_LIB}" ]
then
    EXT_FONT_SIZE="${URXVT_PERL_LIB}/font-size"
    if [ ! -f "${EXT_FONT_SIZE}" ] \
    && command -v curl >/dev/null 2>&1
    then
        curl \
            --create-dirs \
            --output "${EXT_FONT_SIZE}" \
            "https://raw.githubusercontent.com/majutsushi/urxvt-font-size/master/font-size"
    fi
    unset EXT_FONT_SIZE
fi
