;;; ~/.doom.d/init.el -*- lexical-binding: t; -*-

(doom! :completion
       (company
        +auto
        -childframe
        +tng)
       (helm
        -childframe
        +fuzzy)

       :ui
       deft
       doom
       fill-column
       hl-todo
       indent-guides
       modeline
       nav-flash
       ophints
       (popup
        +all
        +defaults)
       pretty-code
       treemacs
       vc-gutter
       vi-tilde-fringe
       (window-select
        +ace-window)
       workspaces

       :editor
       (evil
        +everywhere)
       file-templates
       fold
       (format
        +onsave)
       lispy
       multiple-cursors
       parinfer
       rotate-text
       snippets

       :emacs
       (dired
        +ranger
        +icons)
       electric
       eshell
       imenu
       term
       vc

       :tools
       debugger
       direnv
       eval
       docker
       editorconfig
       ein
       flycheck
       flyspell
       gist
       lookup
       lsp
       magit
       make
       password-store
       pdf
       prodigy
       rgb
       tmux
       upload
       wakatime

       :lang
       assembly
       (cc
        +lsp
        -irony
        -rtags)
       common-lisp
       csharp
       data
       emacs-lisp
       ess
       (go
        +lsp)
       (haskell
        +intero)
       (java
        +meghanada)
       javascript
       latex
       ledger
       markdown
       (org
        +attach
        +babel
        +capture
        +export
        +habit
        +ipython
        +present
        +protocol)
       plantuml
       python
       qt
       racket
       rest
       (sh
        +lsp)
       (web
        -lsp)

       :email
       (mu4e
        +gmail)
       notmuch

       :app
       calendar
       irc
       (rss
        +org)
       twitter
       (write
        +wordnut
        +langtool)

       :config
       (default
        +bindings
        +smartparens))
