---
library: ~/.local/var/lib/beets/library.db
directory: ~/music
plugins: badfiles edit fetchart info mbsync scrub
import:
    write: yes
    copy: no
    move: yes
    bell: yes
match:
    preferred:
        countries: [ 'JP', 'GB|UK', 'US', 'AU', 'RU', 'XE' ]
edit:
    albumfields: album artist albumartist
    itemfields: track title album artist albumartist day month year genre
fetchart:
    auto: yes
    cautious: yes
    cover_names: cover Cover folder Folder art Art album Album front Front
    enforce_ratio: yes
    sources: filesystem coverart itunes amazon albumart wikipedia
scrub:
    auto: yes
