os_build: [
    Linux
]
arch_build: [
    x86,
    x86_64,
    armv5el,
    armv5hf,
    armv6,
    armv7,
    armv7hf,
    armv7s,
    armv7k,
    armv8,
    armv8_32,
    armv8.3
]

os_target: [
    Linux
]
arch_target: [
    x86,
    x86_64,
    armv5el,
    armv5hf,
    armv6,
    armv7,
    armv7hf,
    armv7s,
    armv7k,
    armv8,
    armv8_32,
    armv8.3
]

os:
    Linux:
arch: [
    x86,
    x86_64,
    armv5el,
    armv5hf,
    armv6,
    armv7,
    armv7hf,
    armv7s,
    armv7k,
    armv8,
    armv8_32,
    armv8.3
]
compiler:
    gcc: &gcc
        version: [
            "6.5",
            "7.5",
            "8.4",
            "9.3",
            "10",
            "10.2",
            "10.2.1",
            "11"
        ]
        libcxx: [
            libstdc++,
            libstdc++11
        ]
        threads: [
            None,
            posix
        ]
        exception: [
            None,
            dwarf2,
            sjlj
        ]
        cppstd: [
            None,
            98,
            11,
            14,
            17,
            20
        ]
    clang:
        version: [
            "9",
            "10",
            "11",
            "12",
            "13"
        ]
        libcxx: [
            None,
            libstdc++,
            libstdc++11,
            libc++,
            c++_shared,
            c++_static
        ]
        cppstd: [
            None,
            98,
            11,
            14,
            17,
            20
        ]
        runtime: [
            None,
            MD,
            MT,
            MTd,
            MDd
        ]

build_type: [
    None,
    Debug,
    Release,
    RelWithDebInfo,
    MinSizeRel
]
