set autoindent
set autoread
set backspace=indent,eol,start
set clipboard=unnamedplus,autoselect
set cmdheight=1
set completeopt=menuone,menu,longest
set encoding=utf-8
set exrc
set fileencodings=utf-8
set fileformat=unix
set fillchars+=vert:\
set hidden
set history=512
set hlsearch
set ignorecase
set incsearch
set lazyredraw
set magic
set matchtime=2
set mouse=
set nocompatible
set noerrorbells
set expandtab
set norelativenumber
set noswapfile
set number
set scrolloff=10
set secure
set shiftround
set shiftwidth=4
set showmatch
set showmode
set smartcase
set smartindent
set softtabstop=4
set t_Co=256
set t_vb=
set tm=512
set ttimeoutlen=10
set undolevels=1024
set updatetime=256
set viminfo+=n~/.vim/viminfo
set visualbell
set wildmenu
set wildmode=full
set wrap

colorscheme pablo

syntax on

filetype plugin on
filetype indent on

let mapleader = ','

nnoremap j gj
nnoremap k gk



if empty(glob('~/.vim/autoload/plug.vim'))
    silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
                \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    autocmd VimEnter * PlugInstall --sync | source ~/.vim/vimrc
endif


call plug#begin('~/.vim/plug')

Plug 'airblade/vim-gitgutter'
Plug 'dracula/vim', { 'as': 'dracula'  }
Plug 'farmergreg/vim-lastplace'
Plug 'jiangmiao/auto-pairs'
Plug 'junegunn/fzf'
Plug 'ntpeters/vim-better-whitespace'
Plug 'pbondoer/vim-42header'
Plug 'scrooloose/syntastic'
Plug 'shougo/neocomplete.vim'
Plug 'vim-scripts/ruscmd'
Plug 'editorconfig/editorconfig-vim'

call plug#end()
