#!/bin/sh

[ ! -d "$HOME/.config/mpv" ] && \
    mkdir -p "$HOME/.config/mpv"
[ ! -d "$HOME/.config/mpv/script-opts" ] && \
    mkdir -p "$HOME/.config/mpv/script-opts"

stow \
    --target="$HOME" \
    --ignore="^@.*" \
    --verbose \
    mpv
