#!/bin/sh

[ ! -d "${XDG_CONFIG_HOME}/mpv" ] && \
    mkdir -p "${XDG_CONFIG_HOME}/mpv"
[ ! -d "${XDG_CONFIG_HOME}/mpv/script-opts" ] && \
    mkdir -p "${XDG_CONFIG_HOME}/mpv/script-opts"

stow \
    --target="${HOME}" \
    --ignore="^@.*" \
    --verbose \
    mpv
