#!/bin/sh

[ ! -d "$HOME/.config/gtk-2.0" ] && \
    mkdir -p "$HOME/.config/gtk-2.0"
[ ! -d "$HOME/.config/gtk-3.0" ] && \
    mkdir -p "$HOME/.config/gtk-3.0"

stow \
    --target="$HOME" \
    --ignore="^@.*" \
    --verbose \
    gtk
