#!/bin/sh

[ ! -d "${XDG_CONFIG_HOME}/gtk-2.0" ] && \
    mkdir -p "${XDG_CONFIG_HOME}/gtk-2.0"
[ ! -d "${XDG_CONFIG_HOME}/gtk-3.0" ] && \
    mkdir -p "${XDG_CONFIG_HOME}/gtk-3.0"

stow \
    --target="${HOME}" \
    --ignore="^@.*" \
    --verbose \
    gtk
