#!/bin/sh

if command -v xrdb >/dev/null 2>&1 && [ -f "$HOME/.Xresources" ]
then
    xrdb "$HOME/.Xresources"
fi

if command -v xbindkeys >/dev/null 2>&1 && [ -f "$HOME/.xbindkeysrc" ]
then
    xbindkeys
fi

if command -v hsetroot >/dev/null 2>&1
then
    PAPE="$HOME/pictures/wallpapers/mill.png"
    [ -f "$PAPE" ] && \
        hsetroot -cover "$PAPE"
fi

if command -v unclutter >/dev/null 2>&1
then
    unclutter --timeout 3 --ignore-scrolling --fork
fi

if command -v autocutsel >/dev/null 2>&1
then
    autocutsel -fork && autocutsel -fork -selection PRIMARY
fi

if command -v picom >/dev/null 2>&1
then
    picom --daemon
fi

MPD_CONF="${XDG_CONFIG_HOME}/mpd/mpd.conf"
MPDSCRIBBLE_CONF="${XDG_CONFIG_HOME}/mpdscribble.conf"
if command -v mpd >/dev/null 2>&1 && \
    [ -f "${MPD_CONF}" ] && \
    [ ! -f "/tmp/mpd.pid" ]
then
    mpd "${MPD_CONF}"
fi
if command -v mpdscribble >/dev/null 2>&1 && \
    [ -f "${MPDSCRIBBLE_CONF}" ] && \
    [ -f "/tmp/mpd.pid" ] && \
    [ ! -f "/tmp/mpdscribble.pid" ]
then
    mpdscribble --conf "${MPDSCRIBBLE_CONF}"
fi
unset MPD_CONF
unset MPDSCRIBBLE_CONF

for i in dwm xmonad-ng xmonad
do
    command -v "$i" >/dev/null 2>&1 && \
        exec "$i"
done
