#!/bin/sh

if command -v xrdb >/dev/null 2>&1 && [ -f "$HOME/.Xresources" ]
then
    xrdb "$HOME/.Xresources"
fi

if command -v xbindkeys >/dev/null 2>&1 && [ -f "$HOME/.xbindkeysrc" ]
then
    xbindkeys
fi

if command -v hsetroot >/dev/null 2>&1
then
    PAPE="$HOME/pictures/wallpapers/mill.png"
    [ -f "$PAPE" ] && \
        hsetroot -cover "$PAPE"
fi

if command -v unclutter >/dev/null 2>&1
then
    unclutter --timeout 3 --ignore-scrolling --fork
fi

if command -v autocutsel >/dev/null 2>&1
then
    autocutsel -fork && autocutsel -fork -selection PRIMARY
fi

if command -v picom >/dev/null 2>&1
then
    picom --daemon
fi

for i in dwm xmonad-ng xmonad
do
    command -v "$i" >/dev/null 2>&1 && \
        exec "$i"
done
