#!/bin/sh

[ ! -d "${XDG_CONFIG_HOME}/mpd" ] && \
    mkdir -p "${XDG_CONFIG_HOME}/mpd"
[ ! -d "${XDG_DATA_HOME}/mpd" ] && \
    mkdir -p "${XDG_DATA_HOME}/mpd"
[ ! -d "${XDG_DATA_HOME}/mpd/playlists" ] && \
    mkdir -p "${XDG_DATA_HOME}/mpd/playlists"
[ ! -f "${XDG_DATA_HOME}/mpd/state" ] && \
    touch "${XDG_DATA_HOME}/mpd/state"
[ ! -f "${XDG_DATA_HOME}/mpd/database.gz" ] && \
    touch "${XDG_DATA_HOME}/mpd/database.gz"
[ ! -f "${XDG_DATA_HOME}/mpd/sticker.db" ] && \
    touch "${XDG_DATA_HOME}/mpd/sticker.db"

stow \
    --target="$HOME" \
    --ignore="^@.*" \
    --verbose \
    mpd
