#!/bin/sh

LOCAL="${HOME}/.local"

export XDG_CACHE_HOME="${LOCAL}/var/cache"
export XDG_CONFIG_HOME="${LOCAL}/etc"
export XDG_DATA_HOME="${LOCAL}/var"
export XDG_DESKTOP_DIR="${HOME}/documents"
export XDG_DOCUMENTS_DIR="${HOME}/documents"
export XDG_DOWNLOAD_DIR="${HOME}/downloads"
export XDG_MUSIC_DIR="${HOME}/music"
export XDG_PICTURES_DIR="${HOME}/pictures"
export XDG_PUBLICSHARE_DIR="${HOME}/documents"
export XDG_RUNTIME_DIR="${LOCAL}/run"
export XDG_TEMPLATES_DIR="${HOME}/documents"
export XDG_VIDEOS_DIR="${HOME}/videos"

[ ! -d "${XDG_CACHE_HOME}" ]      && mkdir -p "${XDG_CACHE_HOME}"
[ ! -d "${XDG_CONFIG_HOME}" ]     && mkdir -p "${XDG_CONFIG_HOME}"
[ ! -d "${XDG_DATA_HOME}" ]       && mkdir -p "${XDG_DATA_HOME}"
[ ! -d "${XDG_DESKTOP_DIR}" ]     && mkdir -p "${XDG_DESKTOP_DIR}"
[ ! -d "${XDG_DOCUMENTS_DIR}" ]   && mkdir -p "${XDG_DOCUMENTS_DIR}"
[ ! -d "${XDG_DOWNLOAD_DIR}" ]    && mkdir -p "${XDG_DOWNLOAD_DIR}"
[ ! -d "${XDG_MUSIC_DIR}" ]       && mkdir -p "${XDG_MUSIC_DIR}"
[ ! -d "${XDG_PICTURES_DIR}" ]    && mkdir -p "${XDG_PICTURES_DIR}"
[ ! -d "${XDG_PUBLICSHARE_DIR}" ] && mkdir -p "${XDG_PUBLICSHARE_DIR}"
[ ! -d "${XDG_RUNTIME_DIR}" ]     && mkdir -p "${XDG_RUNTIME_DIR}"
[ ! -d "${XDG_TEMPLATES_DIR}" ]   && mkdir -p "${XDG_TEMPLATES_DIR}"
[ ! -d "${XDG_VIDEOS_DIR}" ]      && mkdir -p "${XDG_VIDEOS_DIR}"
