#!/bin/sh

[ ! -d "${XDG_CONFIG_HOME}/ranger" ] && \
    mkdir -p "${XDG_CONFIG_HOME}/ranger"

stow \
    --target="$HOME" \
    --ignore="^@.*" \
    --verbose \
    ranger

[ ! -f "${XDG_CONFIG_HOME}/ranger/scope.sh" ] && \
    ranger --copy-config=scope.sh
