#!/bin/sh

if command -v xrdb >/dev/null 2>&1 && [ -f "${HOME}/.xresources" ]
then
    xrdb "${HOME}/.xresources"
fi

if command -v xbindkeys >/dev/null 2>&1 && [ -f "${HOME}/.xbindkeysrc" ]
then
    xbindkeys &
fi

if command -v hsetroot >/dev/null 2>&1
then
    if command -v xgetres >/dev/null 2>&1
    then
        hsetroot -solid "$(xgetres color0)"
    else
        PAPE="${HOME}/pictures/wallpapers/mill.png"
        [ -f "${PAPE}" ] && \
            hsetroot -cover "${PAPE}" &
        unset PAPE
    fi
fi

if command -v unclutter >/dev/null 2>&1
then
    unclutter --timeout 3 --ignore-scrolling --fork &
fi

if command -v autocutsel >/dev/null 2>&1
then
    autocutsel -fork &
    autocutsel -fork -selection PRIMARY &
fi

if command -v picom >/dev/null 2>&1
then
    picom --daemon &
fi

MPD_CONF="${XDG_CONFIG_HOME}/mpd/mpd.conf"
MPDSCRIBBLE_CONF="${XDG_CONFIG_HOME}/mpdscribble.conf"
if command -v mpd >/dev/null 2>&1 && \
    [ -f "${MPD_CONF}" ] && \
    [ ! -f "/tmp/mpd.pid" ]
then
    mpd "${MPD_CONF}"

    if command -v mpdscribble >/dev/null 2>&1 && \
        [ -f "${MPDSCRIBBLE_CONF}" ] && \
        [ -f "/tmp/mpd.pid" ] && \
        [ ! -f "/tmp/mpdscribble.pid" ]
    then
        mpdscribble --conf "${MPDSCRIBBLE_CONF}" &
    fi
fi
unset MPD_CONF
unset MPDSCRIBBLE_CONF

for WM in dwm 2bwm xmonad-ng xmonad
do
    command -v "${WM}" >/dev/null 2>&1 && \
        exec "${WM}"
done
