---
library: ~/.var/beets/library.db
directory: ~/music
plugins: discogs edit mbsync fetchart info
format_item: $artist - $album - $title
format_album: $albumartist - $album
sort_item: artist+ album+ disc+ track+
sort_album: albumartist+ album+
sort_case_insensitive: yes
import:
    write: yes
    copy: no
    move: yes
    bell: yes
match:
    preferred:
        countries: [ 'JP', 'US', 'GB|UK', 'RU' ]
paths:
    default: $albumartist/$album%aunique{}/$track $title
edit:
    albumfields: album artist albumartist
    itemfields: track title album artist albumartist day month year genre comment
fetchart:
    auto: yes
    cautious: yes
    cover_names: cover Cover folder Folder
    enforce_ratio: no
    sources: filesystem coverart itunes amazon albumart
    store_source: no
